server:
  port: 9090

spring:
  application:
    name: workflow
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_db
    username: postgres
    password: Shiva@37
    driver-class-name: org.postgresql.Driver 
  main:
    allow-circular-references: true 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  quartz:
    job-store-type: jdbc
    jdbc:
      
      initialize-schema: always 
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            
            dontSetAutoCommitFalse: false

app:
  jwt:
    secret: ${JWT_SECRET:4f6b92a3c8e5d1f0b7a4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2}
    access-token-expiry: 86400000 
    refresh-token-expiry: 604800000
    redirect-url: "http://localhost:9090/api/oauth/notion/callback"
  security:
    secret: ${SECURITY_SECRET:9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c}
  mode: "development"

gemini:
  api:
    key: ${GEMINI_API_KEY:AIzaSyBJsVMlpAbdwnSFIEMCDAou2kmwdQH-SLU}